-- Auto-generated seed data for COS730 Assignment 2 (H2)
-- 15 submissions, 15 reviewers, 45 assignments (3 per submission), 45 review results

DELETE FROM review_result;
DELETE FROM review_assignment;
DELETE FROM reviewer;
DELETE FROM submission;

INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 01', 'research_output_01.pdf', 'application/pdf', 1610537, '11c6974504f888c5b7b60e22be8cea8718c7bd33e79ca33fe9b9085db710a071', 'SUBMITTED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 02', 'research_output_02.pdf', 'application/pdf', 1824890, 'a3231b8ef8e57715964e999bb017ba6837c25aafe976a5095a9010e045b866be', 'ASSIGNED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 03', 'research_output_03.pdf', 'application/pdf', 591397, '4e3b8d79f4e726bb76907f942144b2ddcf184106d216691f9b7b1f74af3b97a7', 'EVALUATED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 04', 'research_output_04.pdf', 'application/pdf', 1539518, '72e4c910f12c3e49cbca05b3298797bd2d023172728842ccc4e54a99a7bc1a7a', 'ASSIGNED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 05', 'research_output_05.pdf', 'application/pdf', 111822, '24989ff8aff67dd2ef4589b69fe25d5baa1a5e3b6bbe5a89a68dcda756c2af11', 'ASSIGNED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 06', 'research_output_06.pdf', 'application/pdf', 1163146, '3807bbc148524081f1dd212fd26519214c79c14c8cda53cc8a03b52919e99c6f', 'SUBMITTED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 07', 'research_output_07.pdf', 'application/pdf', 1959713, 'c3c1987a4bc42506e09cf40402f655b6066d5a417186e1b49fd4059dd799ea5d', 'ASSIGNED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 08', 'research_output_08.pdf', 'application/pdf', 822403, '62a824aa378f9cf6e842632ee6924c781e727cfbf6cc7127ada00db8c1dbcdc9', 'EVALUATED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 09', 'research_output_09.pdf', 'application/pdf', 1919061, '8f5de92bfc3dae7442225816113bd4fd8cd65a1c561f3c13eec81f0a0ad25267', 'SUBMITTED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 10', 'research_output_10.pdf', 'application/pdf', 1421995, '1756bc39f3659b7f5b7f918b2251b332ff67a3ecda26c86d36ed4eb2bc4fbdf4', 'ASSIGNED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 11', 'research_output_11.pdf', 'application/pdf', 1465582, 'd8a6af6fd1713af59e706e31a847d5a9cde557d73f388e899aa33355eba1221b', 'ASSIGNED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 12', 'research_output_12.pdf', 'application/pdf', 1806019, '9881804cc7c60677cf1fac782a5a013fce3b0934d76a602f31305c039b5bd87f', 'EVALUATED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 13', 'research_output_13.pdf', 'application/pdf', 158482, '1e8c90653bf51a3fde690e56473bc1d971e62d641e96096f939c2ec88465cd49', 'EVALUATED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 14', 'research_output_14.pdf', 'application/pdf', 1577779, '748c0a7bd09b9c0a51fca4ebf4c0654a8c09a10387f6b8a94d25cb9f41bc1a4f', 'EVALUATED', CURRENT_TIMESTAMP);
INSERT INTO submission (title, original_filename, content_type, size_bytes, checksum_sha256, status, created_at) VALUES ( 'Research Output 15', 'research_output_15.pdf', 'application/pdf', 1178430, '0b935b0bd232ae0a6f908490c31ad93dfc9115f9bf47fae32e822afc1bd59db4', 'SUBMITTED', CURRENT_TIMESTAMP);

INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 01', 'reviewer01@example.com', 'testing,ml', TRUE, 1);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 02', 'reviewer02@example.com', 'ai,testing', TRUE, 2);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 03', 'reviewer03@example.com', 'security,hci', TRUE, 0);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 04', 'reviewer04@example.com', 'databases,testing', TRUE, 2);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 05', 'reviewer05@example.com', 'security,architecture', TRUE, 1);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 06', 'reviewer06@example.com', 'testing,ai', TRUE, 0);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 07', 'reviewer07@example.com', 'cloud,se', TRUE, 2);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 08', 'reviewer08@example.com', 'se,architecture', TRUE, 2);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 09', 'reviewer09@example.com', 'hci,architecture', TRUE, 2);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 10', 'reviewer10@example.com', 'ai,ml', TRUE, 1);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 11', 'reviewer11@example.com', 'ml,databases', TRUE, 2);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 12', 'reviewer12@example.com', 'networks,testing', TRUE, 2);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 13', 'reviewer13@example.com', 'security,se', TRUE, 1);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 14', 'reviewer14@example.com', 'databases,testing', TRUE, 0);
INSERT INTO reviewer (display_name, email, expertise_tags, active, current_load) VALUES ( 'Reviewer 15', 'reviewer15@example.com', 'cloud,hci', TRUE, 0);


INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (1, 1, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (1, 2, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (1, 3, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (2, 4, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (2, 5, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (2, 6, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (3, 7, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (3, 8, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (3, 9, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (4, 10, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (4, 11, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (4, 12, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (5, 13, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (5, 14, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (5, 15, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (6, 1, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (6, 2, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (6, 3, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (7, 4, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (7, 5, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (7, 6, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (8, 7, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (8, 8, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (8, 9, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (9, 10, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (9, 11, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (9, 12, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (10, 13, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (10, 14, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (10, 15, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (11, 1, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (11, 2, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (11, 3, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (12, 4, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (12, 5, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (12, 6, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (13, 7, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (13, 8, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (13, 9, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (14, 10, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (14, 11, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (14, 12, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (15, 13, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (15, 14, CURRENT_TIMESTAMP, 'ASSIGNED');
INSERT INTO review_assignment (submission_id, reviewer_id, assigned_at, assignment_status) VALUES (15, 15, CURRENT_TIMESTAMP, 'ASSIGNED');



INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (1,  51, 'Auto-generated result for assignment 1', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (1,  44, 'Auto-generated result for assignment 2', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (1,  73, 'Auto-generated result for assignment 3', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (2,  22, 'Auto-generated result for assignment 4', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (2,  20, 'Auto-generated result for assignment 5', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (2,  60, 'Auto-generated result for assignment 6', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (3,  94, 'Auto-generated result for assignment 7', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (3,  90, 'Auto-generated result for assignment 8', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (3,  79, 'Auto-generated result for assignment 9', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (4,  22, 'Auto-generated result for assignment 10', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (4,  23, 'Auto-generated result for assignment 11', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (4,  86, 'Auto-generated result for assignment 12', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (5,  77, 'Auto-generated result for assignment 13', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (5,  47, 'Auto-generated result for assignment 14', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (5,  33, 'Auto-generated result for assignment 15', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (6,  53, 'Auto-generated result for assignment 16', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (6,  29, 'Auto-generated result for assignment 17', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (6,  47, 'Auto-generated result for assignment 18', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (7,  80, 'Auto-generated result for assignment 19', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (7,  20, 'Auto-generated result for assignment 20', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (7,  71, 'Auto-generated result for assignment 21', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (8,  62, 'Auto-generated result for assignment 22', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (8,  73, 'Auto-generated result for assignment 23', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (8,  56, 'Auto-generated result for assignment 24', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (9,  23, 'Auto-generated result for assignment 25', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (9,  70, 'Auto-generated result for assignment 26', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (9,  57, 'Auto-generated result for assignment 27', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (10, 68, 'Auto-generated result for assignment 28', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (10, 24, 'Auto-generated result for assignment 29', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (10, 70, 'Auto-generated result for assignment 30', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (11, 58, 'Auto-generated result for assignment 31', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (11, 81, 'Auto-generated result for assignment 32', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (11, 49, 'Auto-generated result for assignment 33', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (12, 94, 'Auto-generated result for assignment 34', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (12, 90, 'Auto-generated result for assignment 35', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (12, 83, 'Auto-generated result for assignment 36', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (13, 40, 'Auto-generated result for assignment 37', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (13, 38, 'Auto-generated result for assignment 38', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (13, 81, 'Auto-generated result for assignment 39', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (14, 80, 'Auto-generated result for assignment 40', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (14, 56, 'Auto-generated result for assignment 41', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (14, 46, 'Auto-generated result for assignment 42', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (15, 69, 'Auto-generated result for assignment 43', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (15, 50, 'Auto-generated result for assignment 44', CURRENT_TIMESTAMP);
INSERT INTO review_result (submission_id, score, comments, evaluated_at) VALUES (15, 93, 'Auto-generated result for assignment 45', CURRENT_TIMESTAMP);

INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (1, 'REVISION', 56.0);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (2, 'REJECT', 34.0);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (3, 'ACCEPT', 87.7);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (4, 'REJECT', 43.7);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (5, 'REJECT', 52.3);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (6, 'REJECT', 43.0);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (7, 'ACCEPT', 57.0);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (8, 'REVISION', 63.7);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (9, 'REVISION', 50.0);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (10, 'REVISION', 54.0);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (11, 'REVISION', 62.7);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (12, 'ACCEPT', 89.0);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (13, 'REVISION', 53.0);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (14, 'REVISION', 60.7);
INSERT INTO evaluation_outcome (submission_id, final_decision, average_score) VALUES (15, 'ACCEPT', 70.7);
