DROP TABLE IF EXISTS review_result;
DROP TABLE IF EXISTS review_assignment;
DROP TABLE IF EXISTS reviewer;
DROP TABLE IF EXISTS submission;

CREATE TABLE submission
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(255) NOT NULL,
    original_filename VARCHAR(512) NOT NULL,
    content_type      VARCHAR(255) NOT NULL,
    size_bytes        BIGINT       NOT NULL,
    checksum_sha256   VARCHAR(64)  NOT NULL,
    status            VARCHAR(50)  NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reviewer
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name   VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    expertise_tags VARCHAR(512),
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    current_load   INT          NOT NULL DEFAULT 0
);

CREATE TABLE review_assignment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id     BIGINT      NOT NULL,
    reviewer_id       BIGINT      NOT NULL,
    assigned_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assignment_status VARCHAR(50) NOT NULL,

    CONSTRAINT fk_assignment_submission FOREIGN KEY (submission_id) REFERENCES submission (id),
    CONSTRAINT fk_assignment_reviewer FOREIGN KEY (reviewer_id) REFERENCES reviewer (id)
);

CREATE TABLE review_result
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT    NOT NULL,
    score         INT,
    comments      VARCHAR(2000),
    evaluated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_result_submission FOREIGN KEY (submission_id) REFERENCES submission (id)
);

CREATE TABLE evaluation_outcome
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id  BIGINT      NOT NULL,
    final_decision VARCHAR(50) NOT NULL,
    average_score  DOUBLE,
    evaluated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_submission_outcome FOREIGN KEY (submission_id) REFERENCES submission (id)
);

CREATE INDEX idx_submission_status ON submission (status);
CREATE INDEX idx_assignment_submission ON review_assignment (submission_id);
CREATE INDEX idx_assignment_reviewer ON review_assignment (reviewer_id);
