spring.application.name=submission-review-system

# --- H2 (in-memory) ---
spring.datasource.url=jdbc:h2:mem:cos730db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- H2 Console ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=9090

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
